server:
  address: :9526
  model: debug 

db:
  dialects: psql
  host: 127.0.0.1
  port: 5430
  db: go_blog
  username: root
  password: secret
  charset: utf8

  max-idle-conns: 10
  max-open-conns: 100

mylog:
  path: ./log
  name: sys
  model: file
  format: console
  level: debug

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:

jwt:
  issuer: user
  signing-key: mysecret
  access-token-duration: 3h
  refresh-token-duration: 24h
  blacklist_grace_period: 10m
