server:
  address: :9526
  model: debug 

db:
  dialects: psql
  host: 127.0.0.1
  port: 5430
  db: go_blog
  username: root
  password: secret
  charset: utf8

  max-idle-conns: 10
  max-open-conns: 100

mylog:
  path: ./log
  name: sys
  model: file
  format: console
  level: debug

cache:
  expier: 7200
  clearup:  600

jwt:
  signing-key: mysecret
  expires-time: 3h
  issuer: weitim
