package response

import "net/http"

const (
    SUCCESS = http.StatusOK
    ERROR = http.StatusInternalServerError
    BADREQUEST = http.StatusBadRequest
    NOTFOUND = http.StatusNotFound
    FORBIDDEN = http.StatusForbidden

    ERROR_EXIST_TAG = 10001
    ERROR_NOT_EXIST_TAG = 10002
    ERROR_NOT_EXIST_ARTICLE = 10003
    ERROR_AUTH_CHECK_TOKEN_EMPTY = 20001
    ERROR_AUTH_CHECK_TOKEN_FAIL = 20002
    ERROR_AUTH_CHECK_TOKEN_TIMEOUT = 20003
    ERROR_AUTH_CHECK_TOKEN_NOT_FOUND = 20004
    ERROR_AUTH_CHECK_TOKEN_IN_BLACK_LIST = 20005
    ERROR_AUTH_TOKEN = 20006
    ERROR_AUTH = 20007
)