// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: server_blog.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlogServerClient is the client API for BlogServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogServerClient interface {
	LoginBlogger(ctx context.Context, in *LoginBloggerRequest, opts ...grpc.CallOption) (*LoginBloggerResponse, error)
}

type blogServerClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogServerClient(cc grpc.ClientConnInterface) BlogServerClient {
	return &blogServerClient{cc}
}

func (c *blogServerClient) LoginBlogger(ctx context.Context, in *LoginBloggerRequest, opts ...grpc.CallOption) (*LoginBloggerResponse, error) {
	out := new(LoginBloggerResponse)
	err := c.cc.Invoke(ctx, "/pb.BlogServer/LoginBlogger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServerServer is the server API for BlogServer service.
// All implementations must embed UnimplementedBlogServerServer
// for forward compatibility
type BlogServerServer interface {
	LoginBlogger(context.Context, *LoginBloggerRequest) (*LoginBloggerResponse, error)
	mustEmbedUnimplementedBlogServerServer()
}

// UnimplementedBlogServerServer must be embedded to have forward compatible implementations.
type UnimplementedBlogServerServer struct {
}

func (UnimplementedBlogServerServer) LoginBlogger(context.Context, *LoginBloggerRequest) (*LoginBloggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginBlogger not implemented")
}
func (UnimplementedBlogServerServer) mustEmbedUnimplementedBlogServerServer() {}

// UnsafeBlogServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogServerServer will
// result in compilation errors.
type UnsafeBlogServerServer interface {
	mustEmbedUnimplementedBlogServerServer()
}

func RegisterBlogServerServer(s grpc.ServiceRegistrar, srv BlogServerServer) {
	s.RegisterService(&BlogServer_ServiceDesc, srv)
}

func _BlogServer_LoginBlogger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginBloggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServerServer).LoginBlogger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlogServer/LoginBlogger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServerServer).LoginBlogger(ctx, req.(*LoginBloggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlogServer_ServiceDesc is the grpc.ServiceDesc for BlogServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlogServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BlogServer",
	HandlerType: (*BlogServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginBlogger",
			Handler:    _BlogServer_LoginBlogger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_blog.proto",
}
